language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

# faster builds on new travis setup not using sudo
sudo: false

install:
#  - '[[ -z "$CI_USER_TOKEN" ]] || composer config github-oauth.github.com ${CI_USER_TOKEN};'
#  - travis_retry composer self-update && composer --version
#  - travis_retry composer update --prefer-dist --no-interaction

script:
  # This module has no tests yet
  - composer validate --strict
  - php -l src/Codeception/Module/Apc.php
